services:
  app:
    image: openjdk:21-jdk-slim-buster
    container_name: spring-boot-app
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: ["java", "-jar", "fase.one-0.0.1-SNAPSHOT.jar"]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:fase.one
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
